language: swift
os: osx
osx_image: xcode10.2
xcode_project: Tafelsalz.xcodeproj

matrix:
  include:
    - name: "macOS"
      xcode_scheme: Tafelsalz_macOS
    - name: "iOS"
      script:
        - set -o pipefail && xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.2,name=iPhone SE' -project Tafelsalz.xcodeproj -scheme Tafelsalz_iOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty
